### ISSUE TITLE
Can’t update via SideStore

### ISSUE THREAD

**Issue by LucifersCircle** [iKarwan/iNKillerPlus#28]
### Describe the bug

```yaml
I get this error when updating in SideStore:

Instagram could not be installed. The downloaded version of Instagram does not match the version specified by the source.
Expected version: 381.1.0
Found version: 381.1.2
```

### Steps to reproduce

```yaml
Press update on Instagram in SideStore
```

### Crashlog

![Image](https://github.com/user-attachments/assets/30922137-9db8-4e1d-8ad9-6e49aad055f8)

### Post Requisites

- [x] I have checked that a similar issue has not been reported before.
- [x] Verified the relevance of the project and the version you are using.
- [x] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [x] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**
